spring.application.name=paymentservice

spring.liquibase.enabled=true

spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
spring.liquibase.mongodb.url=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=${MONGO_DATABASE}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

api-gateway.url=${API_GATEWAY_URL:http://localhost:8080}
random-number-client.url=https://www.random.org

services.user-service.url=${USER_SERVICE_URL:http://localhost:8081}
services.user-service.name=${USER_SERVICE_NAME:user-service}

keycloak.server-url=${KEYCLOAK_URL:http://localhost:8080}
keycloak.realm=${KEYCLOAK_REALM:master}

spring.security.oauth2.client.registration.keycloak-internal.authorization-grant-type=client_credentials

keycloak.token-url=${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect

spring.security.oauth2.client.registration.keycloak-internal.client-id=${KEYCLOAK_CLIENT_ID:internal-client}
spring.security.oauth2.client.registration.keycloak-internal.client-secret=${KEYCLOAK_CLIENT_SECRET:internal-secret}

spring.security.oauth2.client.provider.keycloak-internal.token-uri=${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/token

spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.server-url}/realms/${keycloak.realm}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.spring.json.add.type.headers=false

payment-service.kafka.topics.payment-created=payment-events
